version: '3.9'

services:
  db:
    container_name: myproject_db
    env_file:
      - .env
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: >
      sh -c "
      pipenv run python manage.py migrate &&
      pipenv run python manage.py runserver 0.0.0.0:8000
      "
    container_name: myproject_web
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/code

volumes:
  postgres_data:
