# Generated by Django 3.2.12 on 2022-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('footprint', models.FloatField(help_text='Use kg of CO2 per unit e.g. burger has 3.5 kg CO2 / burger')),
                ('reference', models.TextField(blank=True, default='', help_text='Use either academic journal or trusted website', null=True)),
            ],
        ),
    ]
